name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      app:
        description: 'Application to deploy (leave empty for all)'
        required: false
        type: string

concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.prototools'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build applications
        run: |
          if [ -n "${{ github.event.inputs.app }}" ]; then
            moon run ${{ github.event.inputs.app }}:build
          else
            moon run :build
          fi

      # Vercel deployment (for Next.js apps)
      - name: Deploy to Vercel
        if: ${{ github.event.inputs.app == '' || contains(github.event.inputs.app, 'web') }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ github.event.inputs.environment == 'production' && '--prod' || '' }}

      # Railway deployment (for backend apps)
      # - name: Deploy to Railway
      #   if: ${{ github.event.inputs.app == '' || contains(github.event.inputs.app, 'api') }}
      #   run: |
      #     railway up --service ${{ github.event.inputs.app || 'api' }}
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Notify deployment
        if: always()
        run: |
          echo "Deployment to ${{ github.event.inputs.environment }} completed"
          echo "Status: ${{ job.status }}"
